### ISSUE TITLE
Fix issue with map sometimes failing for firefox test in the subnet scan

### ISSUE THREAD

**Issue by TheSirLancelot** [TheSirLancelot/Netulla#60]
Every now and then, for unknown reasons, the assertion for the map being visible in the subnet scan fails. It only fails for firefox. Let's figure out a) if we can fix it from failing, or b) if we can assert something different that doesn't rely on the map being visible.

**Comment by tyoung-99** [comment]
The map test has actually been disabled since the problem first occurred, since we couldn't figure out why GitHub's Firefox test would never display the map. I believe the failure that's occurring infrequently is with the table, that either it doesn't display on Firefox sometimes or that Firefox ignores the wait_for() instruction.

I can explore other options for displaying the data to see if that removes the table issue.
